# Generated by Django 4.1.8 on 2023-04-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_economy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabdomain',
            name='id',
        ),
        migrations.AlterField(
            model_name='kabdomain',
            name='domain_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='domain_id'),
        ),
    ]
